// <auto-generated />
using BarlangDoga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarlangDoga.Migrations
{
    [DbContext(typeof(BarlangokDbContext))]
    partial class BarlangokDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BarlangDoga.Models.Barlang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hossz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kiterjedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magassag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Melyseg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
